version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@tinyhttp/app"
    versions:
    - 1.2.18
    - 1.2.20
    - 1.2.21
    - 1.2.23
  - dependency-name: fastify
    versions:
    - 3.11.0
    - 3.12.0
    - 3.13.0
    - 3.14.0
    - 3.14.1
    - 3.14.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
    - 7.2.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.3.0
  - dependency-name: supertest
    versions:
    - 6.1.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
