name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['10', '12', '14', '15']

    name: Node ${{ matrix.node }} testing

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: yarn install --ignore-engines

      - run: yarn test
